#load packages
install.packages("tidyverse")
install.packages("future")
install.packages("furrr")
install.packages("purrr")
install.packages("lubridate")
install.packages("sf")
install.packages("sp")
install.packages("raster")
install.packages("maps")
#install.packages(maptools) -- YA NO EXISTE
#install.packages(rgeo)
library(tidyverse)
library(future)
library(furrr)
library(lubridate)
library(sf)
library(sp)
library(raster)
library(purrr)
library(maps)
#library(maptools)
#library(rgeos)


